jobs:
  build-iso:
    name: 构建镜像
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-unknown-none
          components: rust-src
      - name: 构建
        run: |
          cargo build --release
          mv target/x86_64-kernel/release/kernel iso/boot/kernel
          apt-get update && apt-get install -y grub-common xorriso grub-pc-bin grub-efi-amd64-bin mtools
          grub-mkrescue -o kernel.iso iso
      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: kernel.iso
